config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists, only: [:index, :show, :create, :new] do
    resources :bookmarks, only: [:index, :show, :new, :create, :destroy] do
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :bookmarks, dependent: :delete_all
  has_many :movies, through: :bookmarks
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    # @movies = Movie.all
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def index
    @bookmarks = Bookmark.all
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(params[:list_id])
    else
      render :new
    end
  end

  def destroy
    # raise
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.destroy
      redirect_to list_path(params[:list_id])
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="bookmark_container">
  <h1>Bookmark a movie</h1>

  <%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment, placeholder: :add_a_comment %>
  <%= f.association :movie %>
  <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path("pexels-anthony-157544.jpg")%>)">
    <div class="container">
      <h1>Save your favorite movies</h1>
      <p>When memory fails you, this app saves you</p>
    </div>
  </div>

  <div class="cards">
    <% @lists.each do |list| %>
      <%= link_to list_path(list), class: "text-decoration-none" do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
      <%= list.name %> </div>
      <% end %>
    <% end %>
  </div>

  <%= link_to "Create a new category", new_list_path, class: "btn btn-gradient" %>

</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Create a new list</h1>

  <%= simple_form_for(@list) do |f| %>
  <%= f.input :name, placeholder: :name %>
   <%= f.input :photo, as: :file %>

  <%= f.submit %>
  <% end %>

  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="container">

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path("pexels-anthony-157544.jpg")%>)">
    <%= @list.name %>
  </div>

  <%= link_to "Bookmark a movie", new_list_bookmark_path(@list), class: "btn btn-gradient" %>

  <% @bookmarks.each do |bookmark|%>
    <div class="card-product">
      <img src= <%= bookmark.movie.poster_url %> />
      <div class="card-product-infos">
        <h2><%= bookmark.movie.title %></h2>
        <p><%= bookmark.comment %></p>
        <p><%= link_to 'Delete', list_bookmark_path(@list, bookmark), method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </div>
    </div>
  <% end %>

  <%= link_to "Back to lists", lists_path, class: "btn btn-ghost" %>
</div>